version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    env_file:
      - ../.env.dev
    environment:
      - PORT=8080
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=debug
      - GIN_MODE=debug
    networks:
      - devcontainer_network
    depends_on:
      - redis
    ports:
      - "8080:8080"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - devcontainer_network
    ports:
      - "6379:6379"

networks:
  devcontainer_network:
    driver: bridge

volumes:
  redis-data: